database:
  host: localhost
  port: 5432
  dialect: postgres
  user: postgres
  dbname: im-db
  password: 12345
  gormMaxIdleConn: 20
  gormMaxOpenConn: 300
  gormMaxConnLifetimeHour: 1
  sslmode: disable
  schema: im.

app:
  host: localhost
  port: 8085

jwt:
  secretKey: 9bd82804-970d-44d6-9bc9-f65079ab10dd
  publicKey: secret
  privateKey: secret
  saltKey: salt-key
  accessTokenExpire: 2592000

swagger:
  host: localhost:8080
  scheme: http

#config for server
#swagger:
#  host: main-imd.technofusion.az
#  scheme: https

